# General Application Settings
spring:
  application:
    name: adaa-notification-subscriber # it is used by k8s configmap to pass properties
  banner:
    location: banner/banner.txt
  profiles:
    active: dev # Default profile when none specified on command-line (-Dspring.profiles.active=...)
  main:
    banner-mode: log
  output:
    ansi: enabled
  mvc:
    log-request-details: true

server:
  port: 8080 # works only for embedded tomcat
  servlet:
    application-display-name: ADAA Notification Subscriber
    context-path: /adaa-notification-subscriber
  tomcat:
    cache:
      size: 40960 # cache size of Tomcat (see WebConfig.java)
  compression:
    enabled: false
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
