apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace  }}
  labels:    
    buildNumber: "{{ .Values.buildNumber }}"
    token: "{{ randAlphaNum 10 | lower}}"
  annotations:
    #"helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  keystore_logman_password: {{ .Values.keystore_logman_password | b64enc }}
  keystore_password: {{ .Values.keystore_password | b64enc }}
  truststore_password: {{ .Values.truststore_password | b64enc }}
  keystore: {{ .Values.keystore }}
  truststore: {{ .Values.truststore }}
