apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace  }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    buildNumber: "{{ .Values.buildNumber }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.serviceExternalPort }}
    targetPort: {{ .Values.serviceInternalPort }}
    nodePort: {{ .Values.serviceNodePort }}
    protocol: TCP
    name:
  selector:
    app: {{ template "fullname" . }}
