# OK

POST {{baseBEUri}}/adaa-notification-subscriber/subscriptions/{{subscriptionId}}/events
x-correlation-id: {{zipkinId}}
Accept-Language: CZ
Content-Type: application/json

{
  "eventCount": 5
}

###

# Missing required x-correlation-id

POST {{baseBEUri}}/adaa-notification-subscriber/subscriptions/{{subscriptionId}}/events
Accept-Language: CZ
Content-Type: application/json

{
  "eventCount": 5
}

###

# Missing body

POST {{baseBEUri}}/adaa-notification-subscriber/subscriptions/{{subscriptionId}}/events
x-correlation-id: {{zipkinId}}
Accept-Language: CZ
Content-Type: application/json

###
